services:
  pepper-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pepper-place-web
    restart: unless-stopped
    expose:
      - "80"  # Internal only - Caddy reverse proxy handles external access
    environment:
      - NODE_ENV=production
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  coolify:
    external: true
